### ISSUE TITLE
ImportError: cannot import name properties

### ISSUE THREAD

**Issue by catalinio** [Jerzha/pycom#1]
hi, 

On my setup, macos Sierra 10.12.6, Python 2.7.10, I've "pip install serial", there is this error:

catalins-mbp:pycom catalin$ ./com.py /dev/cu.usbserial-00000000 -b 460800
Traceback (most recent call last):
  File "./com.py", line 5, in <module>
    import serial
  File "/Library/Python/2.7/site-packages/serial/__init__.py", line 1, in <module>
    from serial import properties, meta, model, utilities, errors
  File "/Library/Python/2.7/site-packages/serial/properties.py", line 7, in <module>
    from serial import meta, model
  File "/Library/Python/2.7/site-packages/serial/meta.py", line 12, in <module>
    from serial import model
  File "/Library/Python/2.7/site-packages/serial/model.py", line 15, in <module>
    from serial import properties, meta
ImportError: cannot import name properties

Thanks!

**Comment by catalinio** [comment]
Okey, I've solved it, as "import serial" actually expects pyserial module to be installed, and not serial module (a JSON serializer).. 
I have no idea how python sorted out this.

So, the solution: "sudo pip install pyserial"
